fix_home_nation_location <- function(data){
  
data %>%
  mutate(
    birth_location =
      case_when(
        str_detect(birth_location, "Mozufferpore") ~ paste(birth_location, "India", sep = ", "),
        str_detect(birth_location, "Calcutta") ~ paste(birth_location, "India", sep = ", "),
        str_detect(birth_location, "Velore") ~ paste(birth_location, "India", sep = ", "),
        str_detect(birth_location, "Bangalore") ~ paste(birth_location, "India", sep = ", "),
        str_detect(birth_location, "Bengal") ~ paste(birth_location, "India", sep = ", "),
        str_detect(birth_location, "Cawnpore") ~ paste(birth_location, "India", sep = ", "),
        str_detect(birth_location, "Meerut") ~ paste(birth_location, "India", sep = ", "),
        str_detect(birth_location, "Lahore") ~ paste(birth_location, "India", sep = ", "),
        str_detect(birth_location, "Punjab") ~ paste(birth_location, "India", sep = ", "),
        str_detect(birth_location, "Seoni") ~ paste(birth_location, "India", sep = ", "),
        str_detect(birth_location, "Bombay") ~ paste(birth_location, "India", sep = ", "),
        str_detect(birth_location, "Poona") ~ paste(birth_location, "India", sep = ", "),
        str_detect(birth_location, "Madras") ~ paste(birth_location, "India", sep = ", "),
        str_detect(birth_location, "Mysore") ~ paste(birth_location, "India", sep = ", "),
        str_detect(birth_location, "Bankipore") ~ paste(birth_location, "India", sep = ", "),
        str_detect(birth_location, "Lucknow") ~ paste(birth_location, "India", sep = ", "),
        str_detect(birth_location, "Assam") ~ paste(birth_location, "India", sep = ", "),
        str_detect(birth_location, "Bilasur") ~ paste("Bilaspur", "India", sep = ", "),
        str_detect(birth_location, "Quetta") ~ paste(birth_location, "Pakistan", sep = ", "),
        str_detect(birth_location, "Karachi") ~ paste(birth_location, "Pakistan", sep = ", "),
        str_detect(birth_location, "Darjeeling") ~ paste(birth_location, "India", sep = ", "),
        str_detect(birth_location, "Roorkee") ~ paste(birth_location, "India", sep = ", "),
        str_detect(birth_location, "VIC") ~ paste(birth_location, "Australia", sep = ", "),
        str_detect(birth_location, "Wagga Wagga") ~ paste(birth_location, "Australia", sep = ", "),
        str_detect(birth_location, "NSW") ~ paste(birth_location, "Australia", sep = ", "),
        str_detect(birth_location, "New South Wales") ~ paste(birth_location, "Australia", sep = ", "),
        str_detect(birth_location, "QLD") ~ paste(birth_location, "Australia", sep = ", "),
        str_detect(birth_location, "WA") ~ paste(birth_location, "Australia", sep = ", "),
        str_detect(birth_location, "Darwin") ~ paste(birth_location, "Australia", sep = ", "),
        str_detect(birth_location, "PEI") ~ paste(birth_location, "Canada", sep = ", "),
        str_detect(birth_location, "TAS") ~ paste(birth_location, "Canada", sep = ", "),
        str_detect(birth_location, "BC") ~ paste(birth_location, "Canada", sep = ", "),
        str_detect(birth_location, "AB") ~ paste(birth_location, "Canada", sep = ", "),
        str_detect(birth_location, "MB") ~ paste(birth_location, "Canada", sep = ", "),
        str_detect(birth_location, "ONT") ~ paste(birth_location, "Canada", sep = ", "),
        str_detect(birth_location, "Quebec") ~ paste(birth_location, "Canada", sep = ", "),
        str_detect(birth_location, "Ireland") ~ paste(birth_location),
        str_detect(birth_location, "Cork") ~ paste(birth_location, "Ireland", sep = ", "),
        str_detect(birth_location, "Mullingar") ~ paste(birth_location, "Ireland", sep = ", "),
        str_detect(birth_location, "Wexford") ~ paste(birth_location, "Ireland", sep = ", "),
        str_detect(birth_location, "Co ") ~ paste(birth_location, "Ireland", sep = ", "),
        str_detect(birth_location, "Co. ") ~ paste(birth_location, "Ireland", sep = ", "),
        str_detect(birth_location, "Dublin") ~ paste(birth_location, "Ireland", sep = ", "),
        str_detect(birth_location, "Kildare") ~ paste(birth_location, "Ireland", sep = ", "),
        str_detect(birth_location, "Down") ~ paste(birth_location, "Ireland", sep = ", "),
        str_detect(birth_location, "Antrim") ~ paste(birth_location, "Ireland", sep = ", "),
        str_detect(birth_location, "Tyrone") ~ paste(birth_location, "Ireland", sep = ", "),
        str_detect(birth_location, "Mayo") ~ paste(birth_location, "Ireland", sep = ", "),
        str_detect(birth_location, "Limerick") ~ paste(birth_location, "Ireland", sep = ", "),
        str_detect(birth_location, "Omagh") ~ paste(birth_location, "Ireland", sep = ", "),
        str_detect(birth_location, "Galway") ~ paste(birth_location, "Ireland", sep = ", "),
        str_detect(birth_location, "Monaghan") ~ paste(birth_location, "Ireland", sep = ", "),
        str_detect(birth_location, "Westmeath") ~ paste(birth_location, "Ireland", sep = ", "),
        str_detect(birth_location, "Derry") ~ paste(birth_location, "Ireland", sep = ", "),
        str_detect(birth_location, "Clare") ~ paste(birth_location, "Ireland", sep = ", "),
        str_detect(birth_location, "Tipperary") ~ paste(birth_location, "Ireland", sep = ", "),
        str_detect(birth_location, "Cape") ~ paste(birth_location, "South Africa", sep = ", "),
        str_detect(birth_location, "Basutoland") ~ paste(birth_location, "South Africa", sep = ", "),
        str_detect(birth_location, "Laingsberg") ~ paste(birth_location, "South Africa", sep = ", "),
        str_detect(birth_location, "Nelspruit") ~ paste(birth_location, "South Africa", sep = ", "),
        str_detect(birth_location, "Rondebosch") ~ paste(birth_location, "South Africa", sep = ", "),
        str_detect(birth_location, "Stellenbosch") ~ paste(birth_location, "South Africa", sep = ", "),
        str_detect(birth_location, "Port Elizabeth") ~ paste(birth_location, "South Africa", sep = ", "),
        str_detect(birth_location, "Johannesburg") ~ paste(birth_location, "South Africa", sep = ", "),
        str_detect(birth_location, "Burgersdorp") ~ paste(birth_location, "South Africa", sep = ", "),
        str_detect(birth_location, "fontein") ~ paste(birth_location, "South Africa", sep = ", "),
        str_detect(birth_location, "Vryheid") ~ paste(birth_location, "South Africa", sep = ", "),
        str_detect(birth_location, "Uitenhage") ~ paste(birth_location, "South Africa", sep = ", "),
        str_detect(birth_location, "Pretoria") ~ paste(birth_location, "South Africa", sep = ", "),
        str_detect(birth_location, "Durban") ~ paste(birth_location, "South Africa", sep = ", "),
        str_detect(birth_location, "Klerksdorp") ~ paste(birth_location, "South Africa", sep = ", "),
        str_detect(birth_location, "Middleberg") ~ paste(birth_location, "South Africa", sep = ", "),
        str_detect(birth_location, "Humansdorp") ~ paste(birth_location, "South Africa", sep = ", "),
        str_detect(birth_location, "Dunedin") ~ paste(birth_location, "NZ", sep = ", "),
        str_detect(birth_location, "Turangi") ~ paste(birth_location, "NZ", sep = ", "),
        str_detect(birth_location, "Rotorua") ~ paste(birth_location, "NZ", sep = ", "),
        str_detect(birth_location, "Christchurch$") ~ paste(birth_location, "NZ", sep = ", "),
        str_detect(birth_location, "Auckland") ~ paste(birth_location, "NZ", sep = ", "),
        str_detect(birth_location, "Wellington$") ~ paste(birth_location, "NZ", sep = ", "),
        str_detect(birth_location, "Ngaruawahia") ~ paste(birth_location, "NZ", sep = ", "),
        str_detect(birth_location, " Hutt") ~ paste(birth_location, "NZ", sep = ", "),
        str_detect(birth_location, "Hamilton$") ~ paste(birth_location, "NZ", sep = ", "),
        str_detect(birth_location, "Kaitaia") ~ paste(birth_location, "NZ", sep = ", "),
        str_detect(birth_location, "Otepopo") ~ paste(birth_location, "NZ", sep = ", "),
        str_detect(birth_location, "Tokoroa") ~ paste(birth_location, "NZ", sep = ", "),
        str_detect(birth_location, "Aukland") ~ paste(birth_location, "NZ", sep = ", "),
        str_detect(birth_location, "Opotiki") ~ paste(birth_location, "NZ", sep = ", "),
        str_detect(birth_location, "Waimate") ~ paste(birth_location, "NZ", sep = ", "),
        str_detect(birth_location, "Takapuna") ~ paste(birth_location, "NZ", sep = ", "),
        str_detect(birth_location, "Tauranga") ~ paste(birth_location, "NZ", sep = ", "),
        str_detect(birth_location, "Benin") ~ paste(birth_location, "Nigeria", sep = ", "),
        str_detect(birth_location, "Ibadan") ~ paste(birth_location, "Nigeria", sep = ", "),
        str_detect(birth_location, "Lagos") ~ paste(birth_location, "Nigeria", sep = ", "),
        str_detect(birth_location, "Heidelberg") ~ paste(birth_location, "Germany", sep = ", "),
        str_detect(birth_location, "Rheindalen") ~ paste(birth_location, "Germany", sep = ", "),
        str_detect(birth_location, "Verden") ~ paste(birth_location, "Germany", sep = ", "),
        str_detect(birth_location, "Dusseldorf") ~ paste(birth_location, "Germany", sep = ", "),
        str_detect(birth_location, "Iserlohn") ~ paste(birth_location, "Germany", sep = ", "),
        str_detect(birth_location, "Munich") ~ paste(birth_location, "Germany", sep = ", "),
        str_detect(birth_location, "Wegberg") ~ paste(birth_location, "Germany", sep = ", "),
        str_detect(birth_location, "Aschaffenburg") ~ paste(birth_location, "Germany", sep = ", "),
        str_detect(birth_location, "Nice") ~ paste(birth_location, "France", sep = ", "),
        str_detect(birth_location, "Brussels") ~ paste(birth_location, "Belgium", sep = ", "),
        str_detect(birth_location, "Nuku'alofa") ~ paste(birth_location, "Tonga", sep = ", "),
        str_detect(birth_location, "Nausori") ~ paste(birth_location, "Fiji", sep = ", "),
        str_detect(birth_location, "Lautoka") ~ paste(birth_location, "Fiji", sep = ", "),
        str_detect(birth_location, "Suva") ~ paste(birth_location, "Fiji", sep = ", "),
        str_detect(birth_location, "Castries") ~ paste(birth_location, "Saint Lucia", sep = ", "),
        str_detect(birth_location, "Tientsin") ~ paste(birth_location, "China", sep = ", "),
        str_detect(birth_location, "Shanghai") ~ paste(birth_location, "China", sep = ", "),
        str_detect(birth_location, "Tsengchow") ~ paste(birth_location, "China", sep = ", "),
        str_detect(birth_location, "Waterford") ~ paste(birth_location, "Ireland", sep = ", "),
        str_detect(birth_location, "Meath") ~ paste(birth_location, "Ireland", sep = ", "),
        str_detect(birth_location, "Dungannon") ~ paste(birth_location, "Ireland", sep = ", "),
        str_detect(birth_location, "Londonderry") ~ paste(birth_location, "Ireland", sep = ", "),
        str_detect(birth_location, "Donegal") ~ paste(birth_location, "Ireland", sep = ", "),
        str_detect(birth_location, "Drumkeeran") ~ paste(birth_location, "Ireland", sep = ", "),
        str_detect(birth_location, "Carlow") ~ paste(birth_location, "Ireland", sep = ", "),
        str_detect(birth_location, "Meath") ~ paste(birth_location, "Ireland", sep = ", "),
        str_detect(birth_location, "Roscrea") ~ paste(birth_location, "Ireland", sep = ", "),
        str_detect(birth_location, "Louth") ~ paste(birth_location, "Ireland", sep = ", "),
        str_detect(birth_location, "Kilkenny") ~ paste(birth_location, "Ireland", sep = ", "),
        str_detect(birth_location, "Fermanag") ~ paste(birth_location, "Ireland", sep = ", "),
        str_detect(birth_location, "Ballymayo") ~ paste(birth_location, "Ireland", sep = ", "),
        str_detect(birth_location, "Wicklow") ~ paste(birth_location, "Ireland", sep = ", "),
        str_detect(birth_location, "Nelson") ~ paste(birth_location, "NZ", sep = ", "),
        str_detect(birth_location, "Athlone") ~ paste(birth_location, "Ireland", sep = ", "),
        str_detect(birth_location, "Otahuhu") ~ paste(birth_location, "NZ", sep = ", "),
        str_detect(birth_location, "Canberra") ~ paste(birth_location, "Australia", sep = ", "),
        str_detect(birth_location, "Paris") ~ paste(birth_location, "France", sep = ", "),
        str_detect(birth_location, "Great Barrier Island") ~ paste(birth_location, "NZ", sep = ", "),
        str_detect(birth_location, "Barcelona") ~ paste(birth_location, "Spain", sep = ", "),
        str_detect(birth_location, "Ballincollig") ~ paste(birth_location, "Ireland", sep = ", "),
        str_detect(birth_location, "Hawera") ~ paste(birth_location, "NZ", sep = ", "),
        str_detect(birth_location, "Tullow") ~ paste(birth_location, "Ireland", sep = ", "),
        str_detect(birth_location, "Tiberias") ~ paste(birth_location, "Isreal", sep = ", "),
        str_detect(birth_location, "Dun ") ~ paste(birth_location, "Ireland", sep = ", "),
        str_detect(birth_location, "Aughrim") ~ paste(birth_location, "Spain", sep = ", "),
        str_detect(birth_location, "Cappamore") ~ paste(birth_location, "Ireland", sep = ", "),
        str_detect(birth_location, "Lexlip") ~ paste(birth_location, "Ireland", sep = ", "),
        str_detect(birth_location, "Drogheda") ~ paste(birth_location, "Ireland", sep = ", "),
        str_detect(birth_location, "Whangarei") ~ paste(birth_location, "NZ", sep = ", "),
        str_detect(birth_location, "Feilding") ~ paste(birth_location, "NZ", sep = ", "),
        str_detect(birth_location, "Te Kuiti") ~ paste(birth_location, "NZ", sep = ", "),
        str_detect(birth_location, "Kisumu") ~ paste(birth_location, "Kenya", sep = ", "),
        str_detect(birth_location, "Portlaoise") ~ paste(birth_location, "Ireland", sep = ", "),
        str_detect(birth_location, "Jerusalem") ~ paste(birth_location, "Isreal", sep = ", "),
        str_detect(birth_location, "Enniscorthy") ~ paste(birth_location, "Ireland", sep = ", "),
        str_detect(birth_location, "Kampala") ~ paste(birth_location, "Uganda", sep = ", "),
        str_detect(birth_location, "Ballina") ~ paste(birth_location, "Ireland", sep = ", "),
        str_detect(birth_location, "Laois") ~ paste(birth_location, "Ireland", sep = ", "),
        str_detect(birth_location, "Westport") ~ paste(birth_location, "Ireland", sep = ", "),
        str_detect(birth_location, "Kasauli") ~ paste(birth_location, "India", sep = ", "),
        str_detect(birth_location, "Kinsale") ~ paste(birth_location, "Ireland", sep = ", "),
        str_detect(birth_location, "Clonmel") ~ paste(birth_location, "Ireland", sep = ", "),
        str_detect(birth_location, "Ballybrophy") ~ paste(birth_location, "Ireland", sep = ", "),
        str_detect(birth_location, "Sligo") ~ paste(birth_location, "Ireland", sep = ", "),
        str_detect(birth_location, "Arklow") ~ paste(birth_location, "Ireland", sep = ", "),
        str_detect(birth_location, "Peshawar") ~ paste(birth_location, "India", sep = ", "),
        str_detect(birth_location, "Courtown Harbour") ~ paste(birth_location, "Ireland", sep = ", "),
        str_detect(birth_location, "Queenstown") ~ paste(birth_location, "Ireland", sep = ", "),
        str_detect(birth_location, "Ballyporeen") ~ paste(birth_location, "Ireland", sep = ", "),
        str_detect(birth_location, "Glenbeigh") ~ paste(birth_location, "Ireland", sep = ", "),
        str_detect(birth_location, "Castleisland") ~ paste(birth_location, "Ireland", sep = ", "),
        str_detect(birth_location, "Cookstown") ~ paste(birth_location, "Ireland", sep = ", "),
        str_detect(birth_location, "Thurles") ~ paste(birth_location, "Ireland", sep = ", "),
        str_detect(birth_location, "Ballymena") ~ paste(birth_location, "Ireland", sep = ", "),
        str_detect(birth_location, "Munster") ~ paste(birth_location, "Ireland", sep = ", "),
        str_detect(birth_location, "Longford") ~ paste(birth_location, "Ireland", sep = ", "),
        str_detect(birth_location, "Cashel") ~ paste(birth_location, "Ireland", sep = ", "),
        str_detect(birth_location, "Killiney") ~ paste(birth_location, "Ireland", sep = ", "),
        str_detect(birth_location, "Boghill") ~ paste(birth_location, "Ireland", sep = ", "),
        str_detect(birth_location, "Offaly") ~ paste(birth_location, "Ireland", sep = ", "),
        str_detect(birth_location, "Nenagh") ~ paste(birth_location, "Ireland", sep = ", "),
        str_detect(birth_location, "Enniskillen") ~ paste(birth_location, "Ireland", sep = ", "),
        str_detect(birth_location, "Balghupar") ~ paste(birth_location, "India", sep = ", "),
        str_detect(birth_location, "Clonakilty") ~ paste(birth_location, "Ireland", sep = ", "),
        str_detect(birth_location, "Rathmines") ~ paste(birth_location, "Ireland", sep = ", "),
        str_detect(birth_location, "Queen's") ~ paste(birth_location, "Ireland", sep = ", "),
        str_detect(birth_location, "Mountmellick") ~ paste(birth_location, "Ireland", sep = ", "),
        str_detect(birth_location, "Balbriggan") ~ paste(birth_location, "Ireland", sep = ", "),
        str_detect(birth_location, "Lurgan") ~ paste(birth_location, "Ireland", sep = ", "),
        str_detect(birth_location, "Tralee") ~ paste(birth_location, "Ireland", sep = ", "),
        str_detect(birth_location, "Clonakilty") ~ paste(birth_location, "Ireland", sep = ", "),
        str_detect(birth_location, "Rathmines") ~ paste(birth_location, "Ireland", sep = ", "),
        str_detect(birth_location, "Queen's") ~ paste(birth_location, "Ireland", sep = ", "),
        str_detect(birth_location, "Ferozopore") ~ paste(birth_location, "India", sep = ", "),
        str_detect(birth_location, "Lifford") ~ paste(birth_location, "Ireland", sep = ", "),
        str_detect(birth_location, "Letterkenny") ~ paste(birth_location, "Ireland", sep = ", "),
        str_detect(birth_location, "Geelong") ~ paste(birth_location, "Australia", sep = ", "),
        str_detect(birth_location, "Ambala") ~ paste(birth_location, "Ireland", sep = ", "),
        str_detect(birth_location, "Monkstown") ~ paste(birth_location, "Ireland", sep = ", "),
        str_detect(birth_location, "Kingstown") ~ paste(birth_location, "Ireland", sep = ", "),
        str_detect(birth_location, "Mountmellick") ~ paste(birth_location, "Ireland", sep = ", "),
        str_detect(birth_location, "Monghyr") ~ paste(birth_location),
        str_detect(birth_location, "Abbassia") ~ paste(birth_location),
        str_detect(birth_location, "Dar-") ~ paste(birth_location),
        str_detect(birth_location, "Netherland") ~ paste(birth_location),
        str_detect(birth_location, "Granada") ~ paste(birth_location),
        str_detect(birth_location, "Chingola") ~ paste(birth_location),
        str_detect(birth_location, "Borneo") ~ paste(birth_location),
        str_detect(birth_location, "Philippine") ~ paste(birth_location),
        str_detect(birth_location, "Sanremo") ~ paste(birth_location),
        str_detect(birth_location, "Yokohama") ~ paste(birth_location),
        str_detect(birth_location, "Ceylon") ~ paste(birth_location),
        str_detect(birth_location, "Rhodesia") ~ paste(birth_location),
        str_detect(birth_location, "Africa") ~ paste(birth_location),
        str_detect(birth_location, "United States") ~ paste(birth_location),
        str_detect(birth_location, "Antananarivo") ~ paste(birth_location),
        str_detect(birth_location, "Petrograd") ~ paste(birth_location),
        str_detect(birth_location, "Marondera") ~ paste(birth_location),
        str_detect(birth_location, "Cairo") ~ paste(birth_location),
        str_detect(birth_location, "Burma") ~ paste(birth_location),
        str_detect(birth_location, "Malaya") ~ paste(birth_location),
        str_detect(birth_location, "Buenos Aires") ~ paste(birth_location),
        str_detect(birth_location, "Dacca") ~ paste(birth_location),
        str_detect(birth_location, "Las") ~ paste(birth_location),
        str_detect(birth_location, "UAE") ~ paste(birth_location),
        str_detect(birth_location, "Nairobi") ~ paste(birth_location),
        str_detect(birth_location, "Mozambique") ~ paste(birth_location),
        str_detect(birth_location, "Trinidad") ~ paste(birth_location),
        str_detect(birth_location, "Samoa") ~ paste(birth_location),
        str_detect(birth_location, "Harare") ~ paste(birth_location),
        str_detect(birth_location, "Tsientsin") ~ paste(birth_location),
        str_detect(birth_location, "West Indie") ~ paste(birth_location),
        str_detect(birth_location, "Not ") ~ paste(birth_location),
        TRUE ~ paste(birth_location, "UK", sep = ", ")
      )
  )
}